# Site settings
title: Your Name
description: Personal website and portfolio
author: Your Name

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# URLs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reebot.github.io" # the base hostname & protocol, e.g. http://example.com

# Social media
github_username: reebot
linkedin_username: your-linkedin-username
email: adhikaryreevu97@gmail.com

# Collections
collections:
  projects:
    output: true